config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views
from rest_framework import routers

from pis.views import PiViewSet
from schedules.views import ScheduleViewSet, WindowShowViewSet
from videos.views import VideoViewSet

router = routers.DefaultRouter()
router.register(r'videos', VideoViewSet)
router.register('schedules', ScheduleViewSet)
router.register('pis', PiViewSet)
router.register('windows', WindowShowViewSet)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/callforsubmission.html'), name='home'),
    # url(r'^$', RedirectView.as_view(url=reverse_lazy('videos:videos-add')), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('video_village.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


    # Your stuff: custom urls includes go here
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^videos/', include('videos.urls', namespace='videos')),

    url(r'windows/', include('schedules.urls', namespace='windows')),
    url(r'pis/', include('pis.urls', namespace='pis')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

pis/urls.py
from django.conf.urls import url

from pis.views import projector_off, projector_on

urlpatterns = [
    url(r'^pi/(?P<pk>[\d]+)/projector/off$', projector_off, name='projector_off'),
    url(r'^pi/(?P<pk>[\d]+)/projector/on$', projector_on, name='projector_on'),
]

video_village/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

videos/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from .views import VideoCreate, overview, moderate

urlpatterns = [
    url(r'^add/$', VideoCreate.as_view(), name='add'),
    url(r'^$', overview, name='list'),
    url(r'^moderate/$', moderate, name='moderate'),
    url(r'^moderation/$', TemplateView.as_view(template_name='videos/video_list.html'), name='moderation'),
    url(r'^success/$', TemplateView.as_view(template_name='videos/success.html'), name='success')
    ]

video_village/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

videos/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.db.models import Avg

from localflavor.us.models import USStateField, USZipCodeField, PhoneNumberField
from taggit.managers import TaggableManager

from localflavor.us.models import USStateField, USZipCodeField, PhoneNumberField


class Video(models.Model):
    uploader_name = models.CharField(max_length=255, null=False, blank=True)
    address = models.CharField(max_length=255, null=False, blank=True)
    city = models.CharField(max_length=255, null=False, blank=True)
    state = USStateField(null=True, blank=True)
    zipcode = USZipCodeField(null=True, blank=True)
    phone = PhoneNumberField(null=True, blank=True)
    file = models.FileField()
    title = models.CharField(max_length=255, null=False, blank=True)
    description = models.TextField(null=False, blank=True)
    category = models.CharField(choices=[('D', 'Documentary'), ('N', 'Narrative'), ('A', 'Abstract'), ('An', 'Animation')], max_length=2, null=False, blank=True)
    email = models.EmailField()
    approved = models.BooleanField(default=False)
    status = models.CharField(choices=[('a', 'Approved'), ('r', 'Rejected'), ('s', 'Submitted')], max_length=1, default='s')
    moderated_by = models.ForeignKey('users.User', null=True, blank=True)
    moderation_notes = models.TextField(null=True, blank=True)
    length = models.IntegerField(null=True, blank=True)
    tags = TaggableManager(blank=True)

    def __str__(self):
        return ''.join(('Video: ', self.title, ' ', self.uploader_name))

    def get_absolute_url(self):
        return reverse('api:video-detail', kwargs={'pk': self.pk})

    @property
    def score_avg(self):
        """

        :return: Decimal of the Average Score for the Video
        """
        return self.videoscore_set.aggregate(Avg('score')).get('score__avg')


class VideoScore(models.Model):
    user = models.ForeignKey('users.User')
    video = models.ForeignKey('Video')
    score = models.IntegerField()

    def __str__(self):
        return ' '.join(('User:' + str(self.user),'Video:' + str(self.video),'Score:' + str(self.score)))

videos/forms.py
from django import forms
from .models import Video


class VideoForm(forms.ModelForm):
    file = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))

    class Meta:
        model = Video
        fields = ['uploader_name', 'email', 'phone', 'address', 'city', 'state',
                  'zipcode', 'title', 'description',
                  'category', 'file']

video_village/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

videos/views.py
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse, reverse_lazy
from django.shortcuts import render
from django.template import Context
from django.views.generic import FormView, CreateView
from django.views.generic.edit import ModelFormMixin
from rest_framework import viewsets, generics

from videos.forms import VideoForm
from videos.tables import SimpleTable
from .models import Video
from .serializer import VideoSerializer


class VideoViewSet(viewsets.ModelViewSet):
    """
    API Endpoint for videos.
    """
    queryset = Video.objects.all()
    serializer_class = VideoSerializer


class VideoCreate(CreateView):
    model = Video
    form_class = VideoForm
    success_url = reverse_lazy('videos:success')

    def form_valid(self, form):
        self.object = form.save(commit=False)
        for f in self.request.FILES.getlist('file'):
            self.object.pk = None
            self.object.file = f
            self.object.save()

        return super(VideoCreate, self).form_valid(form)


@login_required
def overview(request):

    mod_queue = Video.objects.filter(approved=False)


    t = 'videos/overview.html'
    c = {
        'moderation_queue_count': len(mod_queue),
        'total_videos': Video.objects.count(),
        'video_table': SimpleTable(Video.objects.all()),
        'awaiting_moderation': mod_queue,
    }

    return render(request, t, c)


@login_required
def moderate(request):

    video_list = Video.objects.all()

    t = 'videos/moderate.html'
    c = {'video_list': video_list}
    return render(request, t, c)

video_village/templates/videos/moderate.html
{% extends 'videos/overview.html' %}

{% block subcontent %}
<h3>Moderation List</h3>
{% endblock subcontent %}

video_village/templates/videos/overview.html
{% extends 'base.html' %}
{% load django_tables2 %}

{% block content %}

    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">
                Dashboard <small>videovillage overview</small>
            </h1>
        </div>
    </div>
    <!-- /.row -->

    <div class="row">
        <div class="col-xl-3 col-lg-6">
            <div class="card card-primary card-inverse">
                <div class="card-header">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-video-camera fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-xs-right">
                            <div class="huge">{{ total_videos }}</div>
                            <div>Total Videos</div>
                        </div>
                    </div>
                </div>
                <div class="card-footer card-default">
                    <a href="{% url 'videos:list' %}">
                        <span class="pull-xs-left">View Details</span>
                        <span class="pull-xs-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6">
            <div class="card {% if awaiting_moderation.count > 0 %}card-yellow{% endif %}{% if awaiting_moderation.count <= 0 %}card-green{% endif %}">
                <div class="card-header">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-video-camera fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-xs-right">
                            <div class="huge">12</div>
                            <div>Awaiting Moderation</div>
                        </div>
                    </div>
                </div>
                <div class="card-footer card-default">
                    <a href="{% url 'videos:moderate' %}">
                        <span class="pull-xs-left">View Details</span>
                        <span class="pull-xs-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6">
            <div class="card card-inverse">
                <div class="card-header card-primary">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-list fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-xs-right">
                            <div class="huge">0</div>
                            <div>Schedules</div>
                        </div>
                    </div>
                </div>
                <div class="card-footer card-default">
                    <a href="javascript:;">
                        <span class="pull-xs-left">View Details</span>
                        <span class="pull-xs-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </a>
                </div>
            </div>
        </div>
        <div class="col-xl-3 col-lg-6">
            <div class="card card-red">
                <div class="card-header card-red">
                    <div class="row">
                        <div class="col-xs-3">
                            <i class="fa fa-pie-chart fa-5x"></i>
                        </div>
                        <div class="col-xs-9 text-xs-right">
                            <div class="huge">0</div>
                            <div>Pi's</div>
                        </div>
                    </div>
                </div>
                <div class="card-footer card-default">
                    <a href="javascript:;">
                        <span class="pull-xs-left">View Details</span>
                        <span class="pull-xs-right"><i class="fa fa-arrow-circle-right"></i></span>
                        <div class="clearfix"></div>
                    </a>
                </div>
            </div>
        </div>
    </div>
    {% block subcontent %}
        <div class="row">
            <div class="col-md-12">
                <h3>All Videos</h3>
                {% render_table video_table %}
            </div>
        </div>
    {% endblock subcontent %}
{% endblock content %}

video_village/templates/videos/success.html
{% extends 'base.html' %}
{% block content %}
<h1>Thank you for your submission!</h1>
{% endblock %}

video_village/templates/videos/video_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <div class="row">
        <div class="col-md-4 col-md-offset-4">
            <form action="" method="post" enctype="multipart/form-data">{% csrf_token %}
                {{ form|crispy }}
                <input type="submit" value="Save" />
            </form>
        </div>
    </div>
{% endblock content %}

video_village/templates/videos/video_list.html
{% extends 'base.html' %}

{% block ng_controller %}VideoController{% endblock %}

{% block content %}
    <h1>Video List</h1>
    {% verbatim %}
        <div class="panel" ng-repeat="video in videos">
            <div class="panel-heading clearfix">
                <h3 class="panel-title">{{ video.title }} - {{ video.name }}</h3>
            </div>
            <p class="well">
                <video width="320" height="240" controls>
                <source src="{{ video.file }}" type="video/mp4">Your browser does not support the video tag.
                </video>
                <a class="btn btn-primary">Approve</a>
                <a class="btn btn-danger">Deny</a>
            </p>
        </div>
    {% endverbatim %}
{% endblock content %}