config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.core.urlresolvers import reverse_lazy
from django.views.generic import TemplateView, RedirectView
from django.views import defaults as default_views
from rest_framework import routers

from pis.views import PiViewSet
from schedules.views import ScheduleViewSet, WindowShowViewSet
from videos.views import VideoViewSet

router = routers.DefaultRouter()
router.register(r'videos', VideoViewSet)
router.register('schedules', ScheduleViewSet)
router.register('pis', PiViewSet)
router.register('windows', WindowShowViewSet)

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='pages/callforsubmission.html'), name='home'),
    # url(r'^$', RedirectView.as_view(url=reverse_lazy('videos:videos-add')), name='home'),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name='about'),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include('video_village.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),


    # Your stuff: custom urls includes go here
    url(r'^api/', include(router.urls, namespace='api')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),


    url(r'^videos/', include('videos.urls', namespace='videos')),

    url(r'windows/', include('schedules.urls', namespace='windows')),
    url(r'pis/', include('pis.urls', namespace='pis')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]

pis/urls.py
from django.conf.urls import url

from pis.views import projector_off, projector_on

urlpatterns = [
    url(r'^pi/(?P<pk>[\d]+)/projector/off$', projector_off, name='projector_off'),
    url(r'^pi/(?P<pk>[\d]+)/projector/on$', projector_on, name='projector_on'),
]

schedules/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required

from .views import WindowList, WindowDetail, all_windows_projector_on, all_windows_projector_off, ShowList, ShowDetail, \
    all_windows_sync, all_windows_cache_clear, all_windows_stream

urlpatterns = [
    url(r'^$', login_required(WindowList.as_view()), name='list'),
    url(r'^shows$', login_required(ShowList.as_view()), name='show_list'),

    url(r'^all_on$', all_windows_projector_on, name='all_on'),
    url(r'^all_off$', all_windows_projector_off, name='all_off'),
    url(r'^all_cache_clear$', all_windows_cache_clear, name='all_cache_clear'),
    url(r'^all_sync$', all_windows_sync, name='all_sync'),

    url(r'^(?P<pk>[\d]+)$', login_required(WindowDetail.as_view()), name='detail'),
    url(r'^shows/(?P<pk>[\d]+)$', login_required(ShowDetail.as_view()), name='show_detail'),


    url(r'^stream$', all_windows_stream, name='stream_form'),


    ]

video_village/users/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url

from . import views

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),

    # URL pattern for the UserRedirectView
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),

    # URL pattern for the UserDetailView
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),

    # URL pattern for the UserUpdateView
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
]

schedules/models.py
"""
Models associated with "shows."

A schedule is a sequence of schedule items.
Each schedule item comprises a date, time, and a show.
A show is a collection of window shows, where a window show
associates a window and a sequence of videos (a "playlist")
to be displayed in that window. A playlist is a sequence of
video segments to be shown, where a video segment could be
either a complete video or an excerpt specified as a start
second and a duration (in seconds).

An artist can set up a playlist. A playlist can be used many times.
A show can be used many times, too. For example, the same show
might run for three nights in a row--the artist would create one
show and then associate it with three schedule items.
"""
from django.core.urlresolvers import reverse
from django.db import models
from videos.models import Video
from django.utils.timezone import now
from datetime import time


class Window(models.Model):
    """
    A window is associated with a pi, a projector, and a screen
    """
    building = models.PositiveIntegerField()
    pi = models.ForeignKey('pis.Pi', null=True, blank=True)
    description = models.CharField(max_length=64, default="?")

    def __str__(self):
        return "Building {} - {}".format(self.building, self.description)

    def get_absolute_url(self):
        return reverse('windows:detail', args=[str(self.id)])

    class Meta(object):
        ordering = ('building',)


class Playlist(models.Model):
    """
    A playlist is a sequence of video segmentss to be played

    Note: The order in which videos play is determined by
    the offset_in_playlist for each video segment in the
    playlist. Care must be taken to ensure that video segments
    do not overlap in a playlist. A gap between two consecutive
    videos is handled by specifying an offset_in_playlist for the
    second video that is greater than the sum of offset_in_playlist
    and duration for the first video.
    """
    title = models.CharField(max_length = 255, blank=True)
    notes = models.TextField(default="", blank=True)

    def __str__(self):
        return self.title


class VideoSegment(models.Model):
    """
    A video segment is a portion of a video that is characterized by three things:
        1. offset (in seconds) within the playlist to start showing this video
        2. offset (in seconds) in the video to start play
        3. duration (in seconds) to play the video
    """
    video = models.ForeignKey(Video, on_delete=models.CASCADE)
    offset_in_playlist = models.PositiveIntegerField(help_text="The number of seconds from the start of the playlist to begin playing a video")
    offset_in_video = models.PositiveIntegerField(default=0, help_text="The number of seconds from the start of the video to begin playing")
    duration = models.PositiveIntegerField(help_text="the length of the video to play (in seconds)")
    lower_third = models.BooleanField(default=False)
    lower_third_duration = models.IntegerField(default=0, null=True, blank=True, help_text="The length of time to show lower third (in seconds)")
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)

    def __str__(self):
        return "[{:>5}] {} - Segment offset {}, duration {} on playlist {}".format(self.offset_in_playlist, self.video, self.offset_in_video, self.duration, self.playlist)


    class Meta(object):
        ordering = ('offset_in_playlist',)


class Show(models.Model):
    """
    A show is a collection of window shows.
    """
    notes = models.TextField(default="")

    def __str__(self):
        return "{:4}: {}".format(self.id, self.notes)

    def get_absolute_url(self):
        return reverse('windows:show_detail', args=[str(self.id)])


class WindowShow(models.Model):
    """
    A show is a display of videos that starts on a given date and a given time.
    A show is associated with a playlist that might repeat.
    """
    show = models.ForeignKey(Show, on_delete=models.CASCADE, help_text="The show this is a part of")
    window = models.ForeignKey(Window, on_delete=models.CASCADE, help_text="The window to be used")
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE, help_text="The playlist to display in this window")
    offset_in_show = models.PositiveIntegerField(default=0, help_text="The number of seconds from the start of the show to delay playing this playlist in this window")
    repeats = models.PositiveIntegerField(default=1, help_text="The number of times to play the playlist (e.g., 1 means play it once)")
    loop = models.BooleanField(default=False, help_text="Should the WindowShow loop until the stop time?")

    def __str__(self):
        return "{}: {} [offset {}] {} (repeats: {})".format(self.window, self.show, self.offset_in_show,
                                                            (self.playlist), self.repeats)

    class Meta(object):
        ordering = ('show', 'offset_in_show', )


class ScheduleItem(models.Model):
    """
    A schedule item is a sequence of shows, each associated with a date and time to start.
    """

    date = models.DateField(default=now, help_text="The date of a show")
    start_time = models.TimeField(default=time(0, 0, 0), help_text="The time a show starts")
    stop_time = models.TimeField(default=time(0, 0, 0), help_text="The time a show stops")
    show = models.ForeignKey(Show, null=True, on_delete=models.CASCADE)

    def __str__(self):
        return "{} {} - Show id {}".format(self.date, self.start_time, str(self.show))

    class Meta(object):
        ordering = ('date', 'start_time', )

# from django.db import models
#
#
# class Window(models.Model):
#     building = models.PositiveIntegerField()
#     pi = models.ForeignKey('pis.Pi', null=True, blank=True)
#
#
# class Showtime(models.Model):
#     date = models.DateField()
#     start_time = models.TimeField()
#     end_time = models.TimeField()
#
#
# class Schedule(models.Model):
#     schedule_start_date = models.DateField()
#     schedule_end_date = models.DateField()
#     repeat = models.BooleanField(default=False)
#     start_delay = models.BigIntegerField(default=0, blank=True)
#     window = models.ForeignKey(Window)
#
#     def __str__(self):
#         return self.schedule_start_date.strftime('%Y-%m-%d') + '  @ Pi:' + str(self.window.pi.mac_address)
#
#     class Meta:
#         unique_together = (('schedule_start_date', 'window'),)
#
#     def duplicate(self, new_start_date, new_end_date, new_window):
#         """
#         Duplicate the Schedule to a new date and/or time
#         :param new_start_date:
#         :param new_end_date:
#         :param new_window:
#         :return:
#         """
#
#
# class ScheduleItem(models.Model):
#     schedule = models.ForeignKey(Schedule, related_name='items')
#     video = models.ForeignKey('videos.Video')
#     video_start_seconds = models.PositiveIntegerField(null=True, blank=True)
#     video_duration_seconds = models.PositiveIntegerField(null=True, blank=True)
#     play_order = models.PositiveIntegerField()
#
#     class Meta:
#         unique_together = (('schedule', 'play_order'),)
#
#     def __str__(self):
#         return str(self.play_order) + ': ' + str(self.video)

video_village/users/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_('Name of User'), blank=True, max_length=255)

    def __str__(self):
        return self.username

    def get_absolute_url(self):
        return reverse('users:detail', kwargs={'username': self.username})

schedules/forms.py
from django import forms

from .models import Window


class StreamForm(forms.Form):
    stream_url = forms.URLField()
    windows = forms.MultipleChoiceField(widget=forms.CheckboxSelectMultiple, label='Windows to Stream to', choices=[])

    def __init__(self):
        super(StreamForm, self).__init__()
        self.fields['windows']['choices'] = [(w.id, w) for w in Window.objects.all()]

schedules/views.py
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.shortcuts import render, redirect
from django.views.generic import DetailView
from django.views.generic import ListView
from rest_framework import viewsets
from rest_framework.decorators import api_view

from schedules.forms import StreamForm
from schedules.models import ScheduleItem, WindowShow, Window, Show
from schedules.serializers import ScheduleItemSerializer, WindowShowSerializer
from video_village.authentication import PiAuthentication


class ScheduleViewSet(viewsets.ModelViewSet):
    """
    API Endpoint for videos.
    """
    queryset = ScheduleItem.objects.all()
    serializer_class = ScheduleItemSerializer


class WindowShowViewSet(viewsets.ModelViewSet):
    queryset = WindowShow.objects.all()
    serializer_class = WindowShowSerializer
    authentication_classes = (PiAuthentication,)

    def get_serializer_context(self):
        context = {}
        show_date = self.request.query_params.get('show_date', None)
        if show_date:
            context = {'date': self.request.query_params.get('show_date')}

        return context



    def get_queryset(self):
        show_date = self.request.query_params.get('show_date', None)
        window = self.request.query_params.get('window', None)
        mac_address = self.request.query_params.get('mac_address', None)

        queryset = WindowShow.objects.all()
        if show_date:
            show_items = ScheduleItem.objects.filter(date=show_date).values_list('show').first()
            if show_items:
                show = show_items[0]
            else:
                show = None
            queryset = queryset.filter(show=show)
            queryset = queryset.filter(show__scheduleitem__date=show_date)

        if window:
            queryset = queryset.filter(window__id=window)

        if mac_address:
            queryset = queryset.filter(window__pi__mac_address=mac_address)

        return queryset


class WindowList(ListView):
    model = Window
    ordering = 'pk'


class WindowDetail(DetailView):
    model = Window


class ShowList(ListView):
    model = Show
    ordering = 'pk'

class ShowDetail(DetailView):
    model = Show

@login_required()
def all_windows_projector_on(request):
    for window in Window.objects.all():
        window.pi.turn_projector_on()
    return JsonResponse({'status': 'OK'})


@login_required()
def all_windows_projector_off(request):
    for window in Window.objects.all():
        window.pi.turn_projector_off()
    return JsonResponse({'status': 'OK'})

@login_required()
def all_windows_cache_clear(request):
    for window in Window.objects.all():
        window.pi.clear_cache()
    return JsonResponse({'status': 'OK'})

@login_required()
def all_windows_sync(request):
    for window in Window.objects.all():
        window.pi.sync()
    return JsonResponse({'status': 'OK'})


@login_required()
def all_windows_stream(request):
    form = StreamForm(request.POST or None)
    if form.is_valid():
        windows = form.cleaned_data['windows']
        url = form.cleaned_data['stream_url']
        for w in windows:
            window = Window.object.get(pk=w)
            window.pi.stream(url)

    t = 'schedules/stream.html'
    return render(request, t, {'form': form})

video_village/users/views.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.core.urlresolvers import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from django.contrib.auth.mixins import LoginRequiredMixin

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):

    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

video_village/templates/schedules/ondemand.html
{% extends 'base.html' %}

{% block content %}
    {{ form.as_p }}
{% endblock %}

video_village/templates/schedules/show_detail.html
{% extends "base.html" %}
{% load static %}


{% block content %}
    <h2>Show: {{ object.notes }}</h2>
    {% for d in object.scheduleitem_set.all %}
        <p>{{ d.date }} - {{ d.start_time }} to {{ d.stop_time }}</p>
    {% endfor %}
    <div class="row">
        <div class="col-xs-6">
            <h3>Windows:</h3>
            {% for w in object.windowshow_set.all %}
                <p>{{ w.window }}</p>
            {% endfor %}
        </div>
        <div class="col-xs-6">
            <img class="img-fluid" src="{% static 'images/floorplan.png' %}">
        </div>
    </div>

{% endblock %}

video_village/templates/schedules/show_list.html
{% extends "base.html" %}

{% block content %}
    <h2>Shows</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Show</th>
                <th>Name</th>
                <th>Window Count</th>
            </tr>
        </thead>
        {% for show in object_list %}
            <tr>
                <td><a href="{{ show.get_absolute_url }}">{{ show.pk }}</td>
                <td>{{ show.notes }}</td>
                <td>{{ show.windowshow_set.count }}</td>
            </tr>

        {% endfor %}
    </table>
{% endblock %}

video_village/templates/schedules/stream.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <form action="stream" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Submit" />
        </form>
{% endblock %}

video_village/templates/schedules/window_detail.html
{% extends "base.html" %}

{% block content %}
    <h2>Window {{ object.pk }}</h2>
    <h3>Location:</h3>
    <p>Building - {{ object.building }}</p>
    <p>Notes - {{ object.notes }}</p>
    <h3>Pi</h3>
    <p>mac address - {{ object.pi.mac_address }}</p>

    <h3>Projector</h3>
    <p>Projector Connected - {{ object.pi.projector_connected }}</p>
    <p>Projector On - {{ object.pi.projector_on }}</p>
    <p>
        {{ object.pi.status }}
    </p>
    <div class="col-xs">
        <h3>Actions:</h3>
        <ul>
            <li><a class="btn btn-success" href="{% url 'pis:projector_on' pk=object.pi.pk %}">Turn Projector On</a></li>
            <li><a class="btn btn-danger" href="{% url 'pis:projector_off' pk=object.pi.pk %}">Turn Projector Off</a></li>
            <li><a class="btn btn-primary" href="{% url 'api:pi-get-status' pk=object.pi.pk %}">Get Status</a></li>
        </ul>
    </div>
    <div class="row">
        <h3>Files</h3>
        <table class="table table-bordered">
            {% for f in object.pi.cachefile_set.all %}
                <tr><td>{{ f.file_name }}</td><td><a class="btn btn-default">Play</a></td></tr>
            {% endfor %}
        </table>
    </div>
{% endblock %}

video_village/templates/schedules/window_list.html
{% extends "base.html" %}

{% block content %}
    <div class="row">
        <a class="btn btn-success" href="{% url 'windows:all_on' %}">All Projectors On</a>
        <a class="btn btn-danger" href="{% url 'windows:all_off' %}">All Projectors Off</a>
        <a class="btn btn-primary" href="{% url 'windows:all_cache_clear' %}">All Cache Clear</a>
        <a class="btn btn-primary" href="{% url 'windows:all_sync' %}">All Windows Sync</a>
    </div>
    <h2>Windows</h2>
    <table class="table">
        <thead>
            <tr>
                <th>Window</th>
                <th>Tunnel URL</th>
                <th>SSH URL</th>
                <th>Projector Connected</th>
                <th>Projector On</th>
                <th>CPU Temp</th>
                <th>Software Version</th>
            </tr>
        </thead>
        {% for window in object_list %}
            <tr>
                <td><a href="{{ window.get_absolute_url }}">{{ window.pk }}</a></td>
                <td>{{ window.pi.tunnel }}</td>
                <td>{{ window.pi.ssh_tunnel }}</td>
                <td class="{% if window.pi.projector_connected %}table-success {% else %}table-danger {% endif %}">{{ window.pi.projector_connected }}</td>
                <td class="{% if window.pi.projector_on %}table-success {% else %}table-danger {% endif %}">{{ window.pi.projector_on }}</td>
                <td>{{ window.pi.cpu_temp }}</td>
                <td>{{ window.pi.software_version }}</td>
            </tr>

        {% endfor %}
    </table>
{% endblock %}